In [1]:
import mysql.connector

In [2]:
# Connect to the MySQL database
connection = mysql.connector.connect(
    host="localhost",       # Database host, usually localhost
    user="root",      # Username you created earlier
    password="ninaanna",    # Password you created earlier
    database="piz"  # The database name
)

# Check if the connection was successful
if connection.is_connected():
    print("Connected to MySQL database")

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [3]:
cursor = connection.cursor()

NameError: name 'connection' is not defined

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Customer_Info (
    customer_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    phonenumber INTEGER,
    streetname VARCHAR(100),
    streetnumber INTEGER,
    zipcode INTEGER,
    gender VARCHAR(100),
    birthdate DATE,
    passkey VARCHAR(10)
);

""")
connection.commit()  # Commit the changes
print("Table `Customer_info` created")

:

In [ ]:
# List of SQL statements for creating tables in the correct order
table_creation_statements = [
    # Tables without foreign key constraints
    """
    CREATE TABLE IF NOT EXISTS Customer_Info (
        customer_id INTEGER PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(100),
        phonenumber BIGINT,
        streetname VARCHAR(100),
        streetnumber INTEGER,
        zipcode INTEGER,
        gender VARCHAR(100),
        birthdate DATE,
        passkey VARCHAR(10)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS discount (
        discount_id INTEGER PRIMARY KEY AUTO_INCREMENT,
        discount_code VARCHAR(10)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS Pizza (
        id INTEGER PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(25),
        description VARCHAR(255),
        base_price INTEGER,
        is_vegetarian BOOLEAN,
        is_vegan BOOLEAN
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS Drink (
        id INTEGER PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(100),
        price INTEGER
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS Dessert (
        id INTEGER PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(100),
        price INTEGER
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS Ingredient (
        id INTEGER PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(25),
        cost INTEGER
    )
    """,
    
    # Tables with foreign key constraints (referenced tables must be created first)
    """
    CREATE TABLE IF NOT EXISTS Orders (
        order_number INTEGER PRIMARY KEY AUTO_INCREMENT,
        customer_id INTEGER,
        date DATE,
        time TIME,
        order_price INTEGER,
        discount_id INTEGER,
        deliveryperson_id INTEGER,
        FOREIGN KEY (customer_id) REFERENCES Customer_Info(customer_id),
        FOREIGN KEY (discount_id) REFERENCES discount(discount_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS DeliveryPerson (
        deliveryperson_id INTEGER PRIMARY KEY AUTO_INCREMENT,
        birthdate DATE,
        phonenumber BIGINT,
        name VARCHAR(25)
        
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS OrderConfirmation (
        order_number INTEGER,
        date DATE,
        time TIME,
        order_price INTEGER,
        estimate_time TIME,
        discount_used BOOLEAN,
        PRIMARY KEY (order_number),
        FOREIGN KEY (order_number) REFERENCES Orders(order_number)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS numberforpizzas (
        customer_id INTEGER,
        number_of_pizzas INTEGER,
        PRIMARY KEY (customer_id),
        FOREIGN KEY (customer_id) REFERENCES Customer_Info(customer_id)
    )
    """,
    
    # Tables with foreign key constraints referencing previously created tables
    """
    CREATE TABLE PizzaOrders (
    pizza_id INT,
    order_number INT,
    PRIMARY KEY (pizza_id, order_number),
    FOREIGN KEY (pizza_id) REFERENCES Pizza(id),
    FOREIGN KEY (order_number) REFERENCES Orders(order_number)
);

    """,
    """
    CREATE TABLE IF NOT EXISTS DrinkOrders (
        drink_id INT,
        order_number INT,
        PRIMARY KEY (drink_id, order_number),
        FOREIGN KEY (drink_id) REFERENCES Drink(id),
        FOREIGN KEY (order_number) REFERENCES Orders(order_number)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS DessertOrders (
        order_number INTEGER,
        dessert_id INT,
        PRIMARY KEY (order_number, dessert_id),
        FOREIGN KEY (order_number) REFERENCES Orders(order_number),
        FOREIGN KEY (dessert_id) REFERENCES Dessert(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS PizzaIngredient (
        pizza_id INTEGER,
        ingredient_id INTEGER,
        PRIMARY KEY (pizza_id, ingredient_id),
        FOREIGN KEY (pizza_id) REFERENCES Pizza(id),
        FOREIGN KEY (ingredient_id) REFERENCES Ingredient(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS PriceCalculation (
        pizza_id INTEGER,
        ingredient_cost_sum INTEGER,
        profit_margin INTEGER,
        vat INTEGER,
        final_price INTEGER,
        PRIMARY KEY (pizza_id),
        FOREIGN KEY (pizza_id) REFERENCES Pizza(id)
    )
    """,
     """
    CREATE TABLE IF NOT EXISTS Registration (
        username VARCHAR(20),
        passkey VARCHAR(20)
    )
    """
]

# Execute each SQL statement
for statement in table_creation_statements:
    try:
        cursor.execute(statement)
        print("Table created successfully")
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        break

# Commit the changes
connection.commit()
print("Tables created successfully")

:

: